### ISSUE TITLE
backpacktf.getBPPrices is not a function

### ISSUE THREAD

**Issue by lukeh990** [charredgrass/node-backpacktf#2]
I am trying to use the getBPPrices with npm backpacktf 0.3.0 but I get this
`TypeError: backpacktf.getBPPrices is not a function
at Object.<anonymous> (/app/index.js:43:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/app/index.js:43
backpacktf.getBPPrices(key, "440", function(err, data) {
           ^
TypeError: backpacktf.getBPPrices is not a function
at Object.<anonymous> (/app/index.js:43:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

**Comment by CRD716** [comment]
same issue here, what's up with that?

**Comment by porkandbeans** [comment]
I encountered this too

backpacktf.getBPPrices is not a function, but I believe it's referring to backpacktf.getCommunityPrices which does the same thing?
